ALTER TABLE public.sales_team
  ADD COLUMN IF NOT EXISTS email TEXT,
  ADD COLUMN IF NOT EXISTS phone TEXT,
  ADD COLUMN IF NOT EXISTS role TEXT,
  ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'active',
  ADD COLUMN IF NOT EXISTS ad_account TEXT,
  ADD COLUMN IF NOT EXISTS bm_name TEXT,
  ADD COLUMN IF NOT EXISTS goal NUMERIC(12,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS region TEXT,
  ADD COLUMN IF NOT EXISTS hired_at DATE,
  ADD COLUMN IF NOT EXISTS notes TEXT;